name: Bump .python-version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # weekly on Monday at 06:00 UTC

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest Python 3.x release
        id: get_latest
        run: |
          curl -s https://www.python.org/downloads/ | grep -oP 'Latest Python 3 Release - Python \K[0-9]+\.[0-9]+\.[0-9]+' | head -1 > /tmp/latest.txt
          LATEST=$(cat /tmp/latest.txt)
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Update runtime.txt if changed
        run: |
          LATEST="${{ steps.get_latest.outputs.latest }}"
          if [ -z "$LATEST" ]; then
            echo "Failed to detect latest Python version; exiting"
            exit 1
          fi
          CUR=$(cat runtime.txt 2>/dev/null || echo "")
          CURRENT_VERSION=${CUR#python-}
          if [ "$CURRENT_VERSION" != "$LATEST" ]; then
            echo "python-$LATEST" > runtime.txt
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add runtime.txt
            git commit -m "chore: bump runtime.txt to python-$LATEST" || true
          else
            echo "runtime.txt already at python-$LATEST"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump runtime.txt to python-${{ steps.get_latest.outputs.latest }}"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          title: "chore: bump runtime.txt to python-${{ steps.get_latest.outputs.latest }}"
          body: "Updates runtime.txt to latest stable Python 3.x release"
          base: master
          branch: "bump-python-version-${{ steps.get_latest.outputs.latest }}"
