name: Check Python dependencies

on:
  schedule:
    - cron: '0 7 * * 1'  # weekly on Monday at 07:00 UTC (after bump-python-version)
  workflow_dispatch:

jobs:
  check-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Python version from runtime.txt
        id: python
        run: |
          VERSION=$(cat runtime.txt | sed 's/python-//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python.outputs.version }}

      - name: Check for dependency updates
        id: check
        run: |
          pip install --upgrade pip
          pip install pip-audit packaging
          
          # Get current requirements
          pip install -q -r requirements.txt 2>/dev/null || true
          
          # Check for outdated packages in each group
          python3 << 'EOF'
          import subprocess
          import json
          
          groups = {
            "data-science": ["numpy", "pandas", "scipy", "matplotlib", "seaborn", "plotly"],
            "bioinformatics": ["biopython", "rpy2"],
            "jupyter": ["jupyter", "notebook", "ipython"]
          }
          
          updates = {}
          for group, packages in groups.items():
            result = subprocess.run(
              ["pip", "list", "--outdated", "--format=json"],
              capture_output=True,
              text=True
            )
            outdated = json.loads(result.stdout)
            group_updates = [p for p in outdated if p['name'] in packages]
            if group_updates:
              updates[group] = group_updates
          
          print(json.dumps(updates, indent=2))
          EOF

      - name: Create Pull Request for updates
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): bump dependencies for Python ${{ steps.python.outputs.version }}"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          title: "chore(deps): update dependencies for Python ${{ steps.python.outputs.version }}"
          body: "Automated dependency update check against Python ${{ steps.python.outputs.version }}"
          base: master
          branch: "deps-update-${{ steps.python.outputs.version }}"
          labels:
            - "dependencies"
            - "python"
          draft: true
